apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::637901591207:role/UdacityFlaskDeployCBKubectlRole
      username: build   
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::637901591207:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-9BG70ZAA79C6
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-11-11T14:18:02Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1684"
  uid: adda754a-b5ed-47cb-a1ba-eff7f320b428
